# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.IntegerField(choices=[(0, 'Student'), (1, 'Teacher')], default=0),
        ),
    ]
