# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 05:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_auto_20170312_1639'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together=set([('user', 'quiz')]),
        ),
    ]
