# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20170313_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.Standard'),
        ),
    ]
