# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20170313_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='district',
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
    ]
