# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20170314_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
