# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20170315_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
