# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20170315_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='city',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
