# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_attempt_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.School'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.City'),
        ),
    ]
